[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hue_marketplace_capstone = "4V8C51KJ45atM2PBmYp91N2tQLHbzMThvMHvvzFKzAQT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
